server:
  port: 8081
spring:
  application:
    name: yeb-server
  profiles:
    include: [secret]
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${wenhe9.mysql.url}
    username: ${wenhe9.mysql.username}
    password: ${wenhe9.mysql.password}
    hikari:
      # 连接池名
      pool-name: DateHikariCP
      # 最小空闲连接数
      minimum-idle: 5
      # 空闲连接最大存活时间 默认 600000（十分钟）
      idle-timeout: 180000
      # 最大连接数 默认10
      maximum-pool-size: 10
      # 从连接池返回的连接的自动提交
      auto-commit: true
      # 连接最大存活时间，0 表示永久存活，默认 1800000 （30分钟）
      max-lifetime: 180000
      # 测试连接是否可用的查询语句
      connection-test-query: SELECT 1
mybatis-plus:
  # 配置mapper映射文件
  mapper-locations: classpath:/mapper/*.xml
  # 配置mybatis数据返回类型别名 （默认别名是类名）
  type-aliases-package: cn.wenhe9.yeb.server.domain
  configuration:
    # 自动驼峰命名
    map-underscore-to-camel-case: true
logging:
  level:
    cn.wenhe9.yeb.server.mapper: debug
jwt:
  # JWT存储的请求头
  tokenHeader: Authorization
  # JWT加解密使用的密钥
  secret: yeb-secret
  # JWT的超时时间（60 * 60 * 24）
  expiration: 604800
  # JWT 负载中拿到开头
  tokenHead: Bearer
